// Package controllersqms provides the HTTP controller logic for the Quarters Management System (QMS).
// It manages the request lifecycle, including decryption of incoming data, security validation,
// quarters data retrieval, and the secure encryption of outgoing responses.
//
// Path : /var/www/html/go_projects/HRMODULE/Final_Mergecode/Meivan/controllers/qms
// --- Creator's Info ---
// Creator:  Elakiya
//
// Created On: 
//
// Last Modified By:
//
// Last Modified Date:
package controllersqms

import (
	"Hrmodule/auth"
	database "Hrmodule/database/qms"
	"Hrmodule/utils"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// Package controllersqms provides the HTTP controller logic for the Quarters Management System (QMS).
// It manages the request lifecycle, including decryption of incoming data, security validation,
// quarters data retrieval, and the secure encryption of outgoing responses.
type QuartersDetailsRequest struct {
	Data string `json:"Data"`
}

// APIResponse defines the standardized JSON structure for all responses 
// generated by the QMS controllers.
type APIResponse struct {
	Status  int         `json:"status"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}


// QuartersDetails handles the retrieval of specific quarters information.
//
// The function performs the following steps:
// 1. Decrypts the incoming AES-GCM encrypted payload using the session-based PID.
// 2. Validates the user token and authorizes the request against API/IP access lists.
// 3. Fetches quarters data from the database based on the decrypted parameters.
// 4. Handles a special case where a record count of zero indicates an "ongoing task."
// 5. Encrypts the final JSON response before sending it back to the client.
func QuartersDetails(w http.ResponseWriter, r *http.Request) {

	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	body, _ := io.ReadAll(r.Body)
	r.Body = io.NopCloser(bytes.NewBuffer(body))
	defer r.Body.Close()

	var req QuartersDetailsRequest
	if err := json.Unmarshal(body, &req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	parts := strings.Split(req.Data, "||")
	if len(parts) != 2 {
		http.Error(w, "Invalid Data format", http.StatusBadRequest)
		return
	}

	pid, encrypted := parts[0], parts[1]

	key, err := utils.GetDecryptKey(pid)
	if err != nil {
		http.Error(w, "Key error", http.StatusUnauthorized)
		return
	}

	decryptedJSON, err := utils.DecryptAES(encrypted, key)
	if err != nil {
		http.Error(w, "Decrypt failed", http.StatusUnauthorized)
		return
	}

	var decryptedData map[string]interface{}
	if err := json.Unmarshal([]byte(decryptedJSON), &decryptedData); err != nil {
		http.Error(w, "Invalid decrypted data", http.StatusBadRequest)
		return
	}

	token := decryptedData["token"].(string)
	r.Header.Set("token", token)

	if !auth.HandleRequestfor_apiname_ipaddress_token(w, r) {
		return
	}

	auth.LogRequestInfo(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		if err := auth.IsValidIDFromRequest(r); err != nil {
			http.Error(w, "Invalid token", http.StatusUnauthorized)
			return
		}

		data, count, err := database.GetQuartersDetailsFromDB(decryptedData)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// ONLY ADDED CONDITION
		if count == 0 {
			resp := APIResponse{
				Status:  200,
				Message: "The task is on going",
				Data:    nil,
			}

			respJSON, _ := json.Marshal(resp)
			encryptedResp, _ := utils.EncryptAES(string(respJSON), key)

			finalResp := map[string]string{
				"Data": fmt.Sprintf("%s||%s", pid, encryptedResp),
			}

			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode(finalResp)
			return
		}

		resp := APIResponse{
			Status:  200,
			Message: "Success",
			Data: map[string]interface{}{
				"no_of_records": count,
				"records":       data,
			},
		}

		respJSON, _ := json.Marshal(resp)
		encryptedResp, _ := utils.EncryptAES(string(respJSON), key)

		finalResp := map[string]string{
			"Data": fmt.Sprintf("%s||%s", pid, encryptedResp),
		}

		auth.SaveResponseLog(
			r,
			finalResp,
			http.StatusOK,
			"application/json",
			len(respJSON),
			string(body),
		)

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(finalResp)

	})).ServeHTTP(w, r)
}
